
/* Peripherals */
#define SOC_GPIO_PIN_CONS_M6_RX   SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_CONS_M6_TX   SOC_UNUSED_PIN // TBD

/* L76K */
#define SOC_GPIO_PIN_GNSS_M6_RX   SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_TX   SOC_UNUSED_PIN // TBD

#define SOC_GPIO_PIN_GNSS_M6_PPS  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_WKE  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_RST  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_SW   SOC_UNUSED_PIN // TBD

/* SPI */
#define SOC_GPIO_PIN_M6_MOSI      _PINNUM(1, 14) // P1.14
#define SOC_GPIO_PIN_M6_MISO      _PINNUM(1, 15) // P1.15
#define SOC_GPIO_PIN_M6_SCK       _PINNUM(1, 13) // P1.13
#define SOC_GPIO_PIN_M6_SS        _PINNUM(1, 12) // P1.12

/* SX1262 */
#define SOC_GPIO_PIN_M6_RST       _PINNUM(1, 10) // P1.10
#define SOC_GPIO_PIN_M6_DIO1      _PINNUM(1,  6) // P1.06
#define SOC_GPIO_PIN_M6_BUSY      _PINNUM(1, 11) // P1.11
