
/* Peripherals */
#define SOC_GPIO_PIN_CONS_M6_RX   _PINNUM(0, 22) // P0.22
#define SOC_GPIO_PIN_CONS_M6_TX   _PINNUM(0, 24) // P0.24

/* L76K */
#define SOC_GPIO_PIN_GNSS_M6_RX   SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_TX   SOC_UNUSED_PIN // TBD

#define SOC_GPIO_PIN_GNSS_M6_PPS  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_WKE  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_RST  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_GNSS_M6_SW   SOC_UNUSED_PIN // TBD

/* SPI */
#define SOC_GPIO_PIN_M6_MOSI      _PINNUM(1, 14) // P1.14
#define SOC_GPIO_PIN_M6_MISO      _PINNUM(1, 15) // P1.15
#define SOC_GPIO_PIN_M6_SCK       _PINNUM(1, 13) // P1.13
#define SOC_GPIO_PIN_M6_SS        _PINNUM(1, 12) // P1.12

/* SX1262 */
#define SOC_GPIO_PIN_M6_RST       _PINNUM(1, 10) // P1.10
#define SOC_GPIO_PIN_M6_DIO1      _PINNUM(1,  6) // P1.06
#define SOC_GPIO_PIN_M6_BUSY      _PINNUM(1, 11) // P1.11

/* I2C */
#define SOC_GPIO_PIN_M6_SDA       _PINNUM(1,  9) // P1.09
#define SOC_GPIO_PIN_M6_SCL       _PINNUM(0,  8) // P0.08

/* button */
#define SOC_GPIO_PIN_M6_BUTTON    SOC_UNUSED_PIN // TBD

/* LED */
#define SOC_GPIO_LED_M6_RED       SOC_UNUSED_PIN // TBD
#define SOC_GPIO_LED_M6_RED_PWR   SOC_UNUSED_PIN // TBD
#define SOC_GPIO_LED_M6_BLUE      SOC_UNUSED_PIN // TBD

/* MX25R1635F SPI flash */
#define SOC_GPIO_PIN_SFL_M6_MOSI  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_SFL_M6_MISO  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_SFL_M6_SCK   SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_SFL_M6_SS    SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_SFL_M6_HOLD  SOC_UNUSED_PIN // TBD
#define SOC_GPIO_PIN_SFL_M6_WP    SOC_UNUSED_PIN // TBD

/* RTC */
#define SOC_GPIO_PIN_RTC_M6_INT   SOC_UNUSED_PIN // TBD

/* ADC */
#define SOC_GPIO_PIN_M6_BATTERY   SOC_UNUSED_PIN // TBD
