
/* TTGO T-BEAM section */
// GNSS module
#define SOC_GPIO_PIN_TBEAM_V05_RX       12
#define SOC_GPIO_PIN_TBEAM_V05_TX       15
#define SOC_GPIO_PIN_TBEAM_V08_RX       34
#define SOC_GPIO_PIN_TBEAM_V08_TX       12
#define SOC_GPIO_PIN_TBEAM_V08_PPS      37
// battery voltage
#define SOC_GPIO_PIN_TBEAM_V05_BATTERY  35
// status LED
#define SOC_GPIO_PIN_TBEAM_LED_V02      21
#define SOC_GPIO_PIN_TBEAM_LED_V05      14
#define SOC_GPIO_PIN_TBEAM_LED_V11      4
// button
#define SOC_GPIO_PIN_TBEAM_V05_BUTTON   39
#define SOC_GPIO_PIN_TBEAM_V08_BUTTON   38
// PMU
#define SOC_GPIO_PIN_TBEAM_V08_PMU_IRQ  35
// SX1276 RESET
#define SOC_GPIO_PIN_TBEAM_RF_RST_V02   SOC_UNUSED_PIN
#define SOC_GPIO_PIN_TBEAM_RF_RST_V05   23
// SX1262 BUSY
#define SOC_GPIO_PIN_TBEAM_RF_BUSY_V08  32
// SX1262 - DIO1, LR1121 - DIO11
#define SOC_GPIO_PIN_TBEAM_RF_DIO1_V08  33
// 1st I2C bus on the T-Beam
#define SOC_GPIO_PIN_TBEAM_SDA          13
#define SOC_GPIO_PIN_TBEAM_SCL          2
