#ifdef ENERGIA_CC1350_LAUNCHXL
#ifndef SMARTRF_SETTINGS_PREDEFINED
#define SMARTRF_SETTINGS_PREDEFINED


//*********************************************************************************
// These settings have been generated for use with TI-RTOS and cc13xxware
//
// Generated by SmartRF Studio version 2.4.3 (build #20)
// Tested for TI-RTOS version tirtos_simplelink_2_21_xx
// Device: CC1350 Rev. 2.1
//
//*********************************************************************************
#include <driverlib/rf_mailbox.h>
#include <driverlib/rf_hs_mailbox.h>
#include <driverlib/rf_common_cmd.h>
#include <driverlib/rf_prop_cmd.h>
#include <driverlib/rf_hs_cmd.h>
#include <ti/drivers/rf/RF.h>

// TX Power dBm lookup table - values from SmartRF Studio
typedef struct {
  int8_t dbm;
  uint16_t txPower; /* Value for the PROP_DIV_RADIO_SETUP.txPower field */
} rfPowerConfig_t;

extern const uint8_t rfPowerTableSize;
extern const rfPowerConfig_t rfPowerTable[];

// RF Core API commands
/* RF command pointers for easylink */
extern RF_Mode *RF_pProp_fsk;
extern RF_Mode *RF_pProp_lrm;
extern RF_Mode *RF_pProp_ook;
extern RF_Mode *RF_pProp_hsm;
extern RF_Mode *RF_pProp_2_4G_fsk;

extern rfc_CMD_PROP_RADIO_DIV_SETUP_t *RF_pCmdPropRadioDivSetup_fsk;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t *RF_pCmdPropRadioDivSetup_lrm;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t *RF_pCmdPropRadioDivSetup_ook;
extern rfc_CMD_RADIO_SETUP_t          *RF_pCmdRadioSetup_hsm;
extern rfc_CMD_PROP_RADIO_SETUP_t *RF_pCmdPropRadioSetup_2_4G_fsk;

extern rfc_CMD_HS_TX_t *RF_pCmdTxHS;
extern rfc_CMD_HS_RX_t *RF_pCmdRxHS;
extern rfc_CMD_FS_t *RF_pCmdFs_preDef;
extern rfc_CMD_PROP_TX_t *RF_pCmdPropTx_preDef;
extern rfc_CMD_PROP_RX_ADV_t *RF_pCmdPropRxAdv_preDef;

#endif // SMARTRF_SETTINGS_PREDEFINED
#endif // ENERGIA_CC1350_LAUNCHXL
